"""create initial schema

Revision ID: 268c1f97178e
Revises: 
Create Date: 2025-06-13 11:53:49.539374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268c1f97178e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competicions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('tipus', sa.Enum('LLIGA', 'COPA', 'MIXTE', name='tipuscompeticioenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('equips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('temporades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('any_inici', sa.Integer(), nullable=False),
    sa.Column('any_fi', sa.Integer(), nullable=False),
    sa.Column('competicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competicio_id'], ['competicions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fases_competicions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('tipus', sa.Enum('LLIGA', 'ELIMINATORIA', name='tipusfaseenum'), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participacions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('equip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equip_id'], ['equips.id'], ),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temporada_id', 'equip_id', name='uq_temporada_equip')
    )
    op.create_table('classificacions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('equip_id', sa.Integer(), nullable=False),
    sa.Column('jornada', sa.Integer(), nullable=False),
    sa.Column('partits_guanyats', sa.Integer(), nullable=False),
    sa.Column('partits_empats', sa.Integer(), nullable=False),
    sa.Column('partits_perduts', sa.Integer(), nullable=False),
    sa.Column('punts', sa.Integer(), nullable=False),
    sa.Column('gols_favor', sa.Integer(), nullable=False),
    sa.Column('gols_contra', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equip_id'], ['equips.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['fases_competicions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fase_id', 'equip_id', 'jornada', name='uq_classificacio_fase')
    )
    op.create_table('partits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('jornada', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('equip_local_id', sa.Integer(), nullable=False),
    sa.Column('equip_visitant_id', sa.Integer(), nullable=False),
    sa.Column('gols_local', sa.Integer(), nullable=True),
    sa.Column('gols_visitant', sa.Integer(), nullable=True),
    sa.Column('partit_anada_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equip_local_id'], ['equips.id'], ),
    sa.ForeignKeyConstraint(['equip_visitant_id'], ['equips.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['fases_competicions.id'], ),
    sa.ForeignKeyConstraint(['partit_anada_id'], ['partits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partits')
    op.drop_table('classificacions')
    op.drop_table('participacions')
    op.drop_table('fases_competicions')
    op.drop_table('temporades')
    op.drop_table('equips')
    op.drop_table('competicions')
    # ### end Alembic commands ###
