"""Afegir data_naixement a Jugador

Revision ID: 415510c50f86
Revises: ef6909d9f754
Create Date: 2025-07-19 02:01:31.752119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415510c50f86'
down_revision: Union[str, None] = 'ef6909d9f754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jugadors', sa.Column('data_naixement', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jugadors', 'data_naixement')
    # ### end Alembic commands ###
