"""Jugadors

Revision ID: 42ad3fb946d4
Revises: c80ec2acfeed
Create Date: 2025-07-19 01:55:43.648545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ad3fb946d4'
down_revision: Union[str, None] = 'c80ec2acfeed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jugadors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('cognom_1', sa.String(length=100), nullable=False),
    sa.Column('cognom_2', sa.String(length=100), nullable=True),
    sa.Column('sobrenom', sa.String(length=100), nullable=True),
    sa.Column('posicio', sa.Enum('POR', 'DEF', 'MIG', 'DAV', name='posicioenum'), nullable=False),
    sa.Column('nacionalitat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nacionalitat'], ['paissos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jugadors_equips_temporades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('equip_id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equip_id'], ['equips.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadors.id'], ),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('classificacions_ibfk_2', 'classificacions', type_='foreignkey')
    op.create_foreign_key(None, 'classificacions', 'fases_competicions', ['fase_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('partits_ibfk_3', 'partits', type_='foreignkey')
    op.create_foreign_key(None, 'partits', 'fases_competicions', ['fase_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partits', type_='foreignkey')
    op.create_foreign_key('partits_ibfk_3', 'partits', 'fases_competicions', ['fase_id'], ['id'])
    op.drop_constraint(None, 'classificacions', type_='foreignkey')
    op.create_foreign_key('classificacions_ibfk_2', 'classificacions', 'fases_competicions', ['fase_id'], ['id'])
    op.drop_table('jugadors_equips_temporades')
    op.drop_table('jugadors')
    # ### end Alembic commands ###
