"""Canvia foto a LONGBLOB

Revision ID: 43d9d2ab62e0
Revises: ce9a479f19ae
Create Date: 2025-06-13 14:56:00.621971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d9d2ab62e0'
down_revision: Union[str, None] = 'ce9a479f19ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competicions', 'foto',
        type_=sa.LargeBinary(length=(2**32)-1),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competicions', 'foto',
        type_=sa.LargeBinary(),  # Torna a BLOB
        existing_nullable=True
    )
    # ### end Alembic commands ###
