"""Taula paissoss

Revision ID: 640c767c158e
Revises: 43d9d2ab62e0
Create Date: 2025-07-03 11:47:09.451929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '640c767c158e'
down_revision: Union[str, None] = '43d9d2ab62e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paissos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('url_imatge', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.add_column('competicions', sa.Column('pais_id', sa.Integer(), nullable=True))
    op.alter_column('competicions', 'foto',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    op.create_foreign_key(None, 'competicions', 'paissos', ['pais_id'], ['id'])
    op.add_column('equips', sa.Column('pais_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equips', 'paissos', ['pais_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equips', type_='foreignkey')
    op.drop_column('equips', 'pais_id')
    op.drop_constraint(None, 'competicions', type_='foreignkey')
    op.alter_column('competicions', 'foto',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('competicions', 'pais_id')
    op.drop_table('paissos')
    # ### end Alembic commands ###
