"""add dorsal fields to jugadors_equips_temporades

Revision ID: a4e1079a6c01
Revises: 22d51f668e3a
Create Date: 2026-01-30 14:56:12.085265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e1079a6c01'
down_revision: Union[str, None] = '22d51f668e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jugadors_equips_temporades', sa.Column('dorsal', sa.Integer(), nullable=True))
    op.add_column('jugadors_equips_temporades', sa.Column('dorsal_start_jornada', sa.Integer(), nullable=True))
    op.add_column('jugadors_equips_temporades', sa.Column('dorsal_end_jornada', sa.Integer(), nullable=True))
    op.add_column('jugadors_equips_temporades', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jugadors_equips_temporades', 'active')
    op.drop_column('jugadors_equips_temporades', 'dorsal_end_jornada')
    op.drop_column('jugadors_equips_temporades', 'dorsal_start_jornada')
    op.drop_column('jugadors_equips_temporades', 'dorsal')
    # ### end Alembic commands ###
