"""url equips

Revision ID: c6ad9dbf7852
Revises: 640c767c158e
Create Date: 2025-07-04 10:22:52.179803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ad9dbf7852'
down_revision: Union[str, None] = '640c767c158e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competicions', 'foto',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('equips', sa.Column('sigles', sa.String(length=10), nullable=False))
    op.add_column('equips', sa.Column('foto', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equips', 'foto')
    op.drop_column('equips', 'sigles')
    op.alter_column('competicions', 'foto',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
