"""no equips

Revision ID: c80ec2acfeed
Revises: c6ad9dbf7852
Create Date: 2025-07-04 12:03:50.971383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80ec2acfeed'
down_revision: Union[str, None] = 'c6ad9dbf7852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporades', sa.Column('numero_equips', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temporades', 'numero_equips')
    # ### end Alembic commands ###
