"""foto competicio

Revision ID: ce9a479f19ae
Revises: 268c1f97178e
Create Date: 2025-06-13 13:31:17.961496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9a479f19ae'
down_revision: Union[str, None] = '268c1f97178e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competicions', sa.Column('foto', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competicions', 'foto')
    # ### end Alembic commands ###
