"""Jugadors

Revision ID: ef6909d9f754
Revises: 42ad3fb946d4
Create Date: 2025-07-19 01:57:44.430640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6909d9f754'
down_revision: Union[str, None] = '42ad3fb946d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jugadors', sa.Column('url_imatge', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jugadors', 'url_imatge')
    # ### end Alembic commands ###
